services:
  # backend:
  #   build:
  #     context: ./app
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - type: bind
  #       source: /home/drater/Documents/Chatapp/app
  #       target: /app
  mysql_db:
    env_file: ./app/.env
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "3307:3306"
    volumes:
      - type: volume
        source: chatapp-db
        target: /var/lib/mysql
volumes:
  chatapp-db:
