services:
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      - APP_ENV=DOCKER
    depends_on:
      mysql_db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./app
        target: /app
      - type: bind
        source: ./database
        target: /database
        read_only: true
  mysql_db:
    env_file: ./app/.env
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p\"$$MYSQL_ROOT_PASSWORD\" --silent"]
      interval: 3s
      timeout: 5s
      retries: 30
      start_period: 60s
    volumes:
      - type: volume
        source: chatapp-db
        target: /var/lib/mysql
  redis:
    env_file: ./app/.env
    image: "redis:alpine"
    ports:
      - "6379:6379"
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports: 
      - "8080:80"
    volumes:
      - type: bind
        source: ./static
        target: /etc/nginx/html
    depends_on:
      backend:
        condition: service_started
volumes:
  chatapp-db:
