services:
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      - APP_ENV=DOCKER
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./app
        target: /app
  mysql_db:
    env_file: ./app/.env
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "3307:3306"
    volumes:
      - type: volume
        source: chatapp-db
        target: /var/lib/mysql
  redis:
    env_file: ./app/.env
    image: "redis:alpine"
    ports:
      - "6379:6379"
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports: 
      - "8080:80"
    volumes:
      - type: bind
        source: ./static
        target: /etc/nginx/html
volumes:
  chatapp-db:
